/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DbDiffRequest } from '../../models/db-diff-request';
import { DiffResponse } from '../../models/diff-response';

export interface DiffDbObject$Params {
      body: DbDiffRequest
}

export function diffDbObject(http: HttpClient, rootUrl: string, params: DiffDbObject$Params, context?: HttpContext): Observable<StrictHttpResponse<DiffResponse>> {
  const rb = new RequestBuilder(rootUrl, diffDbObject.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DiffResponse>;
    })
  );
}

diffDbObject.PATH = '/api/db/diff';
