/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExecuteRequest } from '../../models/execute-request';
import { ExecuteSqlResponse } from '../../models/execute-sql-response';

export interface ExecuteSql$Params {
      body: ExecuteRequest
}

export function executeSql(http: HttpClient, rootUrl: string, params: ExecuteSql$Params, context?: HttpContext): Observable<StrictHttpResponse<ExecuteSqlResponse>> {
  const rb = new RequestBuilder(rootUrl, executeSql.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExecuteSqlResponse>;
    })
  );
}

executeSql.PATH = '/api/execute/sql';
