/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EnvironmentsResponse } from '../../models/environments-response';

export interface ListEnvironments$Params {
}

export function listEnvironments(http: HttpClient, rootUrl: string, params?: ListEnvironments$Params, context?: HttpContext): Observable<StrictHttpResponse<EnvironmentsResponse>> {
  const rb = new RequestBuilder(rootUrl, listEnvironments.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EnvironmentsResponse>;
    })
  );
}

listEnvironments.PATH = '/api/envs';
