/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DeleteResponse } from '../../models/delete-response';

export interface DeleteSession$Params {
  session_id: string;
}

export function deleteSession(http: HttpClient, rootUrl: string, params: DeleteSession$Params, context?: HttpContext): Observable<StrictHttpResponse<DeleteResponse>> {
  const rb = new RequestBuilder(rootUrl, deleteSession.PATH, 'delete');
  if (params) {
    rb.path('session_id', params.session_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DeleteResponse>;
    })
  );
}

deleteSession.PATH = '/api/sessions/{session_id}';
