/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SessionsListResponse } from '../../models/sessions-list-response';

export interface ListSessions$Params {
}

export function listSessions(http: HttpClient, rootUrl: string, params?: ListSessions$Params, context?: HttpContext): Observable<StrictHttpResponse<SessionsListResponse>> {
  const rb = new RequestBuilder(rootUrl, listSessions.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SessionsListResponse>;
    })
  );
}

listSessions.PATH = '/api/sessions';
