/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApplyParamsRequest {
  env_a: string;
  env_b: string;
  name: string;
  new_secret_value?: string;
  new_value: string;
  service: string;
  target?: string;
  value_type?: string;
  with_secret?: boolean;
  write_param?: boolean;
  write_secret?: boolean;
}
