/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateMultiParamsRequest {
  confirm?: boolean;
  create_secret?: boolean;
  dry_run?: boolean;
  envs?: Array<string>;
  name: string;
  secret_name?: string;
  secret_value?: string;
  service?: string;
  value?: string;
  value_type?: string;
}
