/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateSessionRequest {
  alias?: string;
  env_a: string;
  env_b: string;
  keys?: Array<string>;
  reuse?: boolean;
  service?: string;
  title?: string;
}
