/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DbDiffRequest {
  env_a: string;
  env_b: string;
  include_deletes?: boolean;
  object_name: string;
  object_type: string;
  schema_name: string;
}
