/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EnvironmentInfo } from '../models/environment-info';
export interface EnvironmentsResponse {
  config_dir: string;
  environments: Array<EnvironmentInfo>;
  override_set: boolean;
}
