/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EnvironmentInfo {
  env: string;
  load_error?: (string | null);
  profile?: (string | null);
  region?: (string | null);
}
