/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StepResultInfo } from '../models/step-result-info';
export interface ExecuteParamsResponse {
  env_a: string;
  env_b: string;
  message: string;
  name: string;
  ok: boolean;
  op: string;
  service: string;
  steps?: Array<StepResultInfo>;
}
