/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StepCommandInfo } from '../models/step-command-info';
export interface ParamsApplyResponse {
  env_a: string;
  env_b: string;
  name: string;
  script: string;
  service: string;
  steps?: Array<StepCommandInfo>;
}
