/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ParamsDiffResponse {
  changes?: Array<{
[key: string]: any;
}>;
  env_a: string;
  env_b: string;
  is_json?: boolean;
  name: string;
  notes?: Array<string>;
  pair?: boolean;
  param_apply?: (string | null);
  param_needs_write?: boolean;
  param_status?: string;
  patch_value?: (string | null);
  script?: (string | null);
  secret_apply?: (string | null);
  secret_changes?: Array<{
[key: string]: any;
}>;
  secret_needs_write?: boolean;
  secret_patch_value?: (string | null);
  secret_status?: string;
  secret_value_a?: (string | null);
  secret_value_b?: (string | null);
  service: string;
  status: string;
  steps?: Array<{
[key: string]: any;
}>;
  value_a?: (string | null);
  value_b?: (string | null);
  value_type_a?: (string | null);
  value_type_b?: (string | null);
}
