/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ParamsDiffRequest {
  env_a: string;
  env_b: string;
  include_deletes?: boolean;
  name: string;
  service: string;
  with_secret?: boolean;
}
