/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SessionSummaryInfo {
  created_at: string;
  env_a: string;
  env_b: string;
  id: string;
  item_count: number;
  service: string;
  status_counts: {
[key: string]: number;
};
  title: string;
}
