/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SessionSummaryInfo } from '../models/session-summary-info';
export interface SessionsListResponse {
  sessions: Array<SessionSummaryInfo>;
}
