/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateSessionItemRequest {
  diff_err?: (string | null);
  diff_json?: (string | null);
  is_secret?: (boolean | null);
  name: string;
  notes?: (string | null);
  preview?: (string | null);
  script?: (string | null);
  service?: (string | null);
  status?: (string | null);
}
