/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ParamsReadResponse } from '../../models/params-read-response';
import { ReadParamsEntry } from '../../models/read-params-entry';

export interface ParamsRead$Params {
  env: string;
      body: Array<(ReadParamsEntry | string)>
}

export function paramsRead(http: HttpClient, rootUrl: string, params: ParamsRead$Params, context?: HttpContext): Observable<StrictHttpResponse<ParamsReadResponse>> {
  const rb = new RequestBuilder(rootUrl, paramsRead.PATH, 'post');
  if (params) {
    rb.query('env', params.env, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ParamsReadResponse>;
    })
  );
}

paramsRead.PATH = '/api/params/read';
