/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ParameterReadInfo } from '../../models/parameter-read-info';

export interface ParamsGet$Params {
  env: string;
  name: string;
}

export function paramsGet(http: HttpClient, rootUrl: string, params: ParamsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ParameterReadInfo>> {
  const rb = new RequestBuilder(rootUrl, paramsGet.PATH, 'get');
  if (params) {
    rb.query('env', params.env, {});
    rb.query('name', params.name, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ParameterReadInfo>;
    })
  );
}

paramsGet.PATH = '/api/params/get';
