/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExecuteParamsRequest } from '../../models/execute-params-request';
import { ExecuteParamsResponse } from '../../models/execute-params-response';

export interface ParamsApplyExecute$Params {
      body: ExecuteParamsRequest
}

export function paramsApplyExecute(http: HttpClient, rootUrl: string, params: ParamsApplyExecute$Params, context?: HttpContext): Observable<StrictHttpResponse<ExecuteParamsResponse>> {
  const rb = new RequestBuilder(rootUrl, paramsApplyExecute.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExecuteParamsResponse>;
    })
  );
}

paramsApplyExecute.PATH = '/api/params/apply-execute';
