/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApplyParamsRequest } from '../../models/apply-params-request';
import { ParamsApplyResponse } from '../../models/params-apply-response';

export interface ParamsApply$Params {
      body: ApplyParamsRequest
}

export function paramsApply(http: HttpClient, rootUrl: string, params: ParamsApply$Params, context?: HttpContext): Observable<StrictHttpResponse<ParamsApplyResponse>> {
  const rb = new RequestBuilder(rootUrl, paramsApply.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ParamsApplyResponse>;
    })
  );
}

paramsApply.PATH = '/api/params/apply';
